Feature/login 14
sebastien-deren/projet_5_blog_php pull request #47
Opened 2023-01-19 16:02 UTC by sebastien-deren

login_14 #43 is based on register_37 #42 ideally we will merge login into register before merging register into develop, to manage merge conflict more efficiently.

2023-02-01 23:27 UTC, Lionelsan95 requested changes

2023-02-01 23:27 UTC, Lionelsan95 commented on bootstrap.php
> +$router->addPath('connecter', ConnectionController::class);
@sebastien-deren juste pour le style mais c'est bien d'avoir une cohérence pour tes noms de routes. 

soit tu fais tout en français soit tout en anglais

2023-02-01 23:27 UTC, Lionelsan95 commented on src/Controller/User/ConnectionController.php
> +        if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
@sebastien-deren veux-tu vraiment toute ce qui est différent de 'POST' ou 'GET' ? 

En http, tu as plusieurs autres method : PUT, OPTIONS, DELETE, PATCH, etc.

Si c'est 'GET' que tu veux mets le vraiment 

lien des différents méthodes : https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

2023-02-01 23:27 UTC, Lionelsan95 commented on src/Controller/User/RegisterController.php
> +        } else {
@sebastien-deren ce beaucoup d'autres méthodes soit précis dans tes choix 

Je pense que si c'est 'GET', tu acceptes mais les autres non

En général pour les schémas conditionnels, évite le plus possibles les 'else' car trop inclusif

2023-02-01 23:27 UTC, Lionelsan95 commented on src/Entity/User.php
> +        if ($firstname !== \null) {
@sebastien-deren why not yoda style ? :)

2023-02-01 23:27 UTC, Lionelsan95 commented on src/Form/LoginForm.php
> +            throw new \Exception("votre login n'est pas correct, merci de taper un email valide, ou votre username sans espace");
@sebastien-deren concernant les usernames avec des espaces (avant ou après), tu peux être un peu permissif à la fin et faire un trim() pour enlever les espaces avant et après.

Après c'est à toi de décider

2023-02-01 23:27 UTC, Lionelsan95 commented on src/Service/UserService.php
> +    }
@sebastien-deren un peu superflue, tu peux juste utiliser les setters de la classe User

2023-02-01 23:27 UTC, Lionelsan95 commented on src/Service/UserService.php
> +        $loginType = \filter_var($userToLog->login,\FILTER_VALIDATE_EMAIL)?"mail":"login";
@sebastien-deren je vois que c'est un check (valid email or not?) que tu fais très souvent pourquoi pas le mettre dans une méthode qui renvoie ça ? penses-y peut-être

2023-02-01 23:27 UTC, Lionelsan95 commented on template/user/connection.html.twig
> +	</div>
@sebastien-deren ce contenu ne doit pas être afficher quand on est connecté. 

regarde comment mettre un check pas forcément ici dedans mais chez la personne qui l’appelle

2023-02-02 08:04 UTC, sebastien-deren commented on bootstrap.php
> +$router->addPath('connecter', ConnectionController::class);
je suis parti sur tout les noms de routes en anglais, pense tu que "connecter" est un meilleur nom de route que "connection"? (c'est vrai que ça répond mieux a register)

2023-02-02 08:04 UTC, sebastien-deren commented on src/Controller/User/ConnectionController.php
> +        if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
avec le changement dans mon router ce if/else sera remplacé par deux controller indépendant, les seuls méthodes accepté seront alors celle listé dans mon enum method (voir #50 )

2023-02-02 08:05 UTC, sebastien-deren commented on src/Service/UserService.php
> +    }
effectivement, la raison pour laquelle j'avais fait cela comme ça, était de faire évoluer mes méthodes, pour que mes Entité ne sois plus des classes anémiques.

2023-02-02 08:07 UTC, sebastien-deren commented on src/Form/LoginForm.php
> +            throw new \Exception("votre login n'est pas correct, merci de taper un email valide, ou votre username sans espace");
Je ne sais pas encore si l'username ne pourrait pas servir de pseudo (par exemple pour les commentaire) si c'est le cas je pense faire un regex pour être encore plus limitatif sur les username (pour avoir des pseudo lisible)

2023-02-06 22:42 UTC, Lionelsan95 approved these changes

2023-02-07 08:09 UTC, merged